version: "3.8"
services:
  db:
    image: postgres
    container_name: rent-a-car-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rent-a-car-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root