CREATE TABLE ENGINES
(
    ENGINE_ID   SERIAL UNIQUE,
    ENGINE_NAME VARCHAR(20)
);

CREATE INDEX ENGINE_ID_INDEX ON ENGINES (ENGINE_ID);

CREATE TABLE CARS
(
    CAR_ID    SERIAL UNIQUE,
    CAR_NAME  VARCHAR(20),
    CAR_YEAR  INTEGER,
    ENGINE_FK INTEGER,
    FOREIGN KEY (ENGINE_FK) REFERENCES ENGINES (ENGINE_ID)
);

CREATE INDEX CAR_ID_INDEX ON CARS (CAR_ID);

INSERT INTO ENGINES(ENGINE_ID, ENGINE_NAME)
VALUES (DEFAULT, '1.8'),
       (DEFAULT, '1.2'),
       (DEFAULT, '1.6'),
       (DEFAULT, '1.8'),
       (DEFAULT, '2.0');

INSERT INTO CARS(CAR_ID, CAR_NAME, CAR_YEAR, ENGINE_FK)
VALUES (DEFAULT, 'HRV', 2020, 1),
       (DEFAULT, 'DS 7', 2021, 3),
       (DEFAULT, 'Q3', 202, 4);